// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcc7UHp-sZfWVWmcD9Hlb84FIQtp7v-mI',
    appId: '1:275792359493:web:2f7de2997864c4b8d3332c',
    messagingSenderId: '275792359493',
    projectId: 'auth-tutorial-826a3',
    authDomain: 'auth-tutorial-826a3.firebaseapp.com',
    storageBucket: 'auth-tutorial-826a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1_s61AVXhRT1d5ikMIfIy7vAf9YXBVg',
    appId: '1:275792359493:android:301c432fa123384fd3332c',
    messagingSenderId: '275792359493',
    projectId: 'auth-tutorial-826a3',
    storageBucket: 'auth-tutorial-826a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6jGAMv3m69WYv5gDoIqu2gTtk-BwgoWw',
    appId: '1:275792359493:ios:d810c2cd40c92f18d3332c',
    messagingSenderId: '275792359493',
    projectId: 'auth-tutorial-826a3',
    storageBucket: 'auth-tutorial-826a3.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6jGAMv3m69WYv5gDoIqu2gTtk-BwgoWw',
    appId: '1:275792359493:ios:b687e221365e5e32d3332c',
    messagingSenderId: '275792359493',
    projectId: 'auth-tutorial-826a3',
    storageBucket: 'auth-tutorial-826a3.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
